language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: kruegg21
  password:
    secure: OXJoY7Xl0Ca6ZNbSeLTMt11C1VdH/cI7D5EN7SJQoNVfwTuUPEtJXmHhYbveYYx4WeOdeyi6qiuGo4P87dvwPbc53ja6l2t0fIAD2k5UUEEuFlNbs7GvIEozUb50vH2zPreIkP6oz9tLx+oC7FvYDvWZuGBuPriZfehDq0dt11GzT/p5CLvejStgdgWhPKwVNWWXABFuHuyFByOpfpcEXx64Zr4aKbkZE4iKduU/iSIHEJ61gKBN6ZEglRmgzLRj5vqAKT246a/dw/yCtqiiLtuK+W4QrH10GWwc5lQnlo/IEefNQhhXZokcT0pDHjTggvYn8UXIUkSyYqrvOa8kXtYwVIJTNa9d92ee1M/RC6YiykKMJSZ2nodrbwBIEYXKIBjpBP60SUjtUxoY3qZGnjiSE4hd+RKGrjtEbD/hCbIZjgAgh76HNSPBt783vEPSACK0+DW00aXj6hUyEjBKMO4dFcMPH4Hev+dguOsyzuyrmKoIeAhbGuteOpQMiLzy9Zg6pYV7MVaO3kmaN1GBn1hLIvGY7IW/gwxSH8nOMfycX1n8TJefE8nqZbeXiSiuu2I3iTij+958rZIgyDoax+BsicLzbbbNPy/ssG5+IbhmB154Ylun900dvSwk60GuQP/uKKv3arfWO0aRpzft5CuyDRFMD6pyd249T5LaZvU=
  on:
    tags: true
    repo: kruegg21/ga_data_api
    python: 3.6
